apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: coremark
  namespace: default
spec:
  benchmarkOperator:
    name: none
    namespace: default
  benchmarkSpec: |
    parallelism: 1
    backoffLimit: 0
    template:
      spec:
        containers:
          - name: coremark
            image: ghcr.io/sunya-ch/coremark:ubi
            env:
            - name: THREADNUM
              value: "1thread"
            command:
            - sh
            - -c
            - ./coremark-${THREADNUM}.exe
        restartPolicy: Never
  parserKey: coremark
  repetition: 5
  iterationSpec:
    iterations:
    - location: .template.spec.containers[0].env[name=THREADNUM].value
      name: t
      values:
      - "4threads"
      - "8threads"
      - "12threads"
      - "16threads"
      - "20threads"
      - "24threads"
      - "28threads"
      - "32threads"
    - location: .parallelism
      name: parallelism
    sequential: true