apiVersion: batch/v1
kind: Job
metadata:
  name: tpcc-data-load
  namespace: cockroach-operator-system
spec:
  template:
    spec:
      containers:
        - name: driver
          image: ghcr.io/sunya-ch/cockroach/tpcc:latest
          env:
          - name: cockroach0
            value: postgres://root@cockroach-release-cockroachdb-0.cockroach-release-cockroachdb.cockroach-operator-system.svc.cluster.local:26257?sslmode=disable
          - name: warehouse
            value: "1000"
          - name: active_warehouse
            value: "1000"
          command: ["/bin/bash", "-c"]
          args:
          - /root/tpcc.sh -d 1m -W $warehouse -A $active_warehouse $cockroach0 && cat /root/tpcc-results/tpcc-results-${active_warehouse}.txt
      restartPolicy: Never
  backoffLimit: 4